version: '3.8'
services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/var/www/html'
            - '/var/www/html/vendor/'
        ports:
            - "80:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true

