version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/var/www/html'
            - '/var/www/html/vendor/'
        ports:
            - "80:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
    db:
        image: mysql:8.2
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            # So you don't have to use root, but you can if you like
            MYSQL_USER: ${DB_USERNAME}
            # You can use whatever password you like
            MYSQL_PASSWORD: ${DB_PASSWORD}
            # Password for root access
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - '3306:3306'
        expose:
            - '3306'
        # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql

# Name our volume
volumes:
    my-db:
