name: Unit Testing

on:
  pull_request:
    branches: [ 'main' ]
  push:
    branches: [ '*' ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run composer install
        working-directory: ./laravel-app
        run: composer install

      - name: Migrate SQLite Database
        working-directory: ./laravel-app
        run: php artisan migrate --env=testing

      - name: Run tests
        working-directory: ./laravel-app
        run: php artisan test --parallel --env=testing
